server:
  port: 8761
  

#Eureka Settings
#Only in Branch
eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: https://cloud-hero.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/